<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/01_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch is an open-source machine learning framework that is widely used for deep learning applications. It was primarily developed by Facebook's AI Research lab (FAIR) and is known for its flexibility, ease of use, and dynamic computation graph.

In [1]:
import torch

Tensors in PyTorch are the fundamental data structure, similar to NumPy's ndarray, but with the added capability to utilize GPUs for accelerated computing

In [5]:
x=torch.empty(2,3) ## torch.empty gives you un-initialized memory or garbage
x

tensor([[3.5940e-18, 0.0000e+00, 0.0000e+00],
        [1.5046e-36, 8.3637e-22, 0.0000e+00]])

In [6]:
x=torch.rand(2,2) ## torch.rand creates tensors and assign some random values or Uniform(0, 1) random sample.
x

tensor([[0.9022, 0.4428],
        [0.4464, 0.8316]])

In [7]:
x=torch.zeros(2,2) ## torch.zeroes initializes with zeros
x

tensor([[0., 0.],
        [0., 0.]])

In [8]:
x=torch.ones(2,3) ## initailizes with ones
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x=torch.ones(2,2,dtype=torch.int) ## we can change the datatype as well
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [10]:
x.size() ## prints the size of x

torch.Size([2, 2])

In [11]:
x=torch.tensor([2.5,0.1]) ##torch.tensor(data) creates a new tensor by copying the given Python/NumPy data.
x

tensor([2.5000, 0.1000])

In [16]:
# performing some basic operations
# 1. ADDITION
x=torch.rand(2,2)
y=torch.rand(2,2)

print(x)
print(y)

## z=x+y
# OR
'''z=torch.add(x,y)
print(z)'''
# OR
y.add_(x) ## inplace addition
print(y)



tensor([[0.4114, 0.8675],
        [0.1005, 0.0163]])
tensor([[0.8478, 0.0253],
        [0.2235, 0.7418]])
tensor([[1.2592, 0.8928],
        [0.3240, 0.7581]])


In [18]:
# 2. SUBTRACTION

## z=x-y
# OR
'''z=torch.sub(x,y)
print(z)'''
# OR
y.sub_(x) ## inplace subtraction
print(y)

tensor([[ 0.4364, -0.8422],
        [ 0.1229,  0.7254]])


In [20]:
# 3. MULTIPLICATION

## z=x*y
# OR
'''z=torch.mul(x,y)
print(z)'''
# OR
y.mul_(x) ## inplace multiplication
print(y)

tensor([[ 7.3861e-02, -6.3382e-01],
        [ 1.2423e-03,  1.9374e-04]])


In [22]:
# 4. DIVISION

## z=x/y
# OR
'''z=torch.div(x,y)
print(z)'''
# OR
y.div_(x) ## inplace division
print(y)

tensor([[ 0.1795, -0.7306],
        [ 0.0124,  0.0119]])


In [25]:
# Slicing operations

x=torch.rand(5,3)
print(x)
print(x[1,:]) # prints second row all columns

tensor([[0.4004, 0.9400, 0.6950],
        [0.9922, 0.3390, 0.8529],
        [0.2720, 0.6686, 0.9887],
        [0.2183, 0.4094, 0.3658],
        [0.7765, 0.7471, 0.0649]])
tensor([0.9922, 0.3390, 0.8529])


In [27]:
print(x[1,1].item()) ## .item gives the complete value

0.3390173316001892


In [30]:
x=torch.rand(4,4)
print(x)
y=x.view(16) ## .view reshapes the tensor
print(y)
z=x.view(-1,8) ## the size -1 is inferred from other dimensions
print(z)

## reshapes x into a 2-D tensor whose second dimension is fixed at 8 columns; PyTorch automatically computes the required number of rows (–1) so the total element count stays the same

tensor([[0.8748, 0.2267, 0.8573, 0.0536],
        [0.7665, 0.3971, 0.4276, 0.0752],
        [0.7836, 0.2181, 0.7811, 0.0217],
        [0.5400, 0.7282, 0.0495, 0.3923]])
tensor([0.8748, 0.2267, 0.8573, 0.0536, 0.7665, 0.3971, 0.4276, 0.0752, 0.7836,
        0.2181, 0.7811, 0.0217, 0.5400, 0.7282, 0.0495, 0.3923])
tensor([[0.8748, 0.2267, 0.8573, 0.0536, 0.7665, 0.3971, 0.4276, 0.0752],
        [0.7836, 0.2181, 0.7811, 0.0217, 0.5400, 0.7282, 0.0495, 0.3923]])


In [31]:
## converting numpy to pytorch

import numpy as np

In [34]:
a=torch.ones(5)
print(a)

b=a.numpy()
print(type(b))

print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


b = a.numpy() gives a NumPy array that shares the same memory with the PyTorch tensor a;
any in-place change to a (like a.add_(1)) is instantly reflected in b because both point to the identical underlying buffer.

In [36]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [40]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

a+=1
print(a)
print(b)

## because both(numpy array and tensor) of them are pointing to same memory locations , so both are gonna get modified

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [47]:
## here we check whether is the cuda or gpu is available or not
## if available we will perform the action there which would be much more fater than running any instances on the cpu

if torch.cuda.is_available():
  device=torch.device("cuda")
  x=torch.onesI(5,device=device)
  y=torch.ones(5)
  y=y.to(device)
  z=x+y
  z=z.to("cpu") ## back to cpu

requires_grad=True tells PyTorch to track every operation on that tensor so it can compute gradients later (for back-propagation).

In [48]:
x=torch.ones(5,requires_grad=True) #by default it is false
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
