<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/pytorch001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cu128


In [2]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


#### creating tensors


In [4]:
# empty
a=torch.empty(2,3) ## assigns a space in memory and returns already stored value

In [5]:
# type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# rand
torch.rand(2,3) # between 0 and 1

tensor([[0.6443, 0.3453, 0.7829],
        [0.5115, 0.5414, 0.8281]])

In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3) # helps in reproduction

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#### tensor shapes

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [17]:
# same shape tensor
torch.empty_like(x)

tensor([[          422833072,           422223984,   72340172838076673],
        [3979322135920521473,                  48,                  48]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#### tensor datatypes

In [22]:
# find data type
x.dtype

torch.int64

In [23]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
# using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#### mathematical operations

##### 1. scaler operations

In [29]:
x=torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [30]:
# addition
x + 2

# subtraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100)//3

# mod
((x * 100)/3) % 2

# power
x**2


tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

##### 2. element wise operations


In [33]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])
tensor([[0.3182, 0.5261, 0.0447],
        [0.5123, 0.9051, 0.5989]])


In [34]:
# add
a + b

# sub
a - b

# multiply
a * b

# division
a / b

# power
a ** b

# mod
a % b


tensor([[0.1629, 0.3641, 0.0250],
        [0.0359, 0.6476, 0.3430]])

In [38]:
c=torch.tensor([1,-2,3,-4])


In [39]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
# negative
torch.neg(c)


tensor([-1,  2, -3,  4])

In [41]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])


In [47]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [48]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [50]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

##### 3.reduction operation

In [54]:
e = torch.randint(size=(2, 3), low=0, high=10,dtype=torch.float32)
e

tensor([[0., 4., 3.],
        [8., 8., 3.]])

In [55]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)


tensor([ 7., 19.])

In [57]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

# mean along row
torch.mean(e, dim=1)

tensor([2.3333, 6.3333])

In [60]:
# median
torch.median(e)

# max and min
torch.max(e)
torch.min(e)

# product
torch.prod(e)

# standard deviation
torch.std(e)

# variance
torch.var(e)

# arg max
torch.argmax(e)

# arg min
torch.argmin(e)

tensor(0)

##### 4. matrix operations

In [61]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)


tensor([[3, 5, 0],
        [6, 4, 0]])
tensor([[8, 4],
        [7, 2],
        [3, 8]])


In [63]:
# matrix multiplication
torch.matmul(f,g)

tensor([[59, 22],
        [76, 32]])

In [64]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)


tensor(11)

In [65]:
# transpose

torch.transpose(f,0,1)

tensor([[3, 6],
        [5, 4],
        [0, 0]])

In [66]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h


tensor([[5., 6., 2.],
        [9., 5., 0.],
        [4., 2., 7.]])

In [67]:
# determinant

torch.det(h)

tensor(-207.)

In [68]:
# inverse

torch.inverse(h)

tensor([[-0.1691,  0.1836,  0.0483],
        [ 0.3043, -0.1304, -0.0870],
        [ 0.0097, -0.0676,  0.1401]])

##### 5. comparsion operations

In [69]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)


tensor([[1, 1, 5],
        [4, 4, 1]])
tensor([[1, 2, 4],
        [7, 2, 5]])


In [70]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

# greater than equal to
i >= j

# less than equal to
i <= j


tensor([[ True,  True, False],
        [ True, False,  True]])

##### 7. special operations


In [76]:
k = torch.randint(size=(2, 3), low=0, high=10,dtype=torch.float32)
k

tensor([[2., 3., 1.],
        [0., 2., 1.]])

In [77]:
# log
torch.log(k)

tensor([[0.6931, 1.0986, 0.0000],
        [  -inf, 0.6931, 0.0000]])

In [78]:
# exponent
torch.exp(k)

tensor([[ 7.3891, 20.0855,  2.7183],
        [ 1.0000,  7.3891,  2.7183]])

In [79]:
# square root
torch.sqrt(k)

tensor([[1.4142, 1.7321, 1.0000],
        [0.0000, 1.4142, 1.0000]])

In [80]:
# sigmoid
torch.sigmoid(k)


tensor([[0.8808, 0.9526, 0.7311],
        [0.5000, 0.8808, 0.7311]])

In [81]:
# softmax
torch.softmax(k,dim=1)

tensor([[0.2447, 0.6652, 0.0900],
        [0.0900, 0.6652, 0.2447]])

In [82]:
# relu
torch.relu(k)

tensor([[2., 3., 1.],
        [0., 2., 1.]])

##### inplace operations


In [83]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])
tensor([[0.2499, 0.3206, 0.9753],
        [0.7582, 0.6688, 0.2651]])


In [85]:
m.add_(n) # updates m by storing n

tensor([[1.2339, 1.4910, 2.8617],
        [2.0011, 2.2812, 0.9207]])

In [86]:
m

tensor([[1.2339, 1.4910, 2.8617],
        [2.0011, 2.2812, 0.9207]])

In [87]:
m.relu_()

tensor([[1.2339, 1.4910, 2.8617],
        [2.0011, 2.2812, 0.9207]])

##### copy a tensor

In [90]:
a=torch.rand(2,3)
a

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [91]:
b=a.clone()

In [92]:
a

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [93]:
b

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [94]:
a[0][0]=10

In [95]:
a

tensor([[10.0000,  0.5057,  0.5688],
        [ 0.0634,  0.8993,  0.2732]])

In [96]:
b

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [97]:
id(a)

136751051406096

In [98]:
id(b)

136751053599472

#### tensor operations on gpu

In [99]:
torch.cuda.is_available()

True

In [100]:
device=torch.device('cuda')

In [101]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)


tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [102]:
# moving an existing tensor to GPU
a = torch.rand((2, 3))
a


tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]])

In [103]:
a.to(device)

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]], device='cuda:0')

In [104]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 14.8435 seconds
Time on GPU: 0.6938 seconds

Speedup (CPU time / GPU time): 21.394979838113834


#### reshaping tensors

In [105]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [107]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
b = torch.rand(2,3,4)
b

tensor([[[0.8801, 0.4203, 0.8186, 0.0463],
         [0.7306, 0.2009, 0.3265, 0.6684],
         [0.3509, 0.7772, 0.2353, 0.4301]],

        [[0.4385, 0.7375, 0.5494, 0.7109],
         [0.0148, 0.7262, 0.4660, 0.0610],
         [0.7108, 0.5127, 0.8211, 0.1323]]])

In [112]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [113]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [114]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

#### Numpy and Pytorch

In [115]:
import numpy as np

In [116]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [117]:
b=a.numpy()

In [118]:
b

array([1, 2, 3])

In [120]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [121]:
torch.from_numpy(c)

tensor([1, 2, 3])