<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/pytorch_like()functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

torch.zeros_like(input)
* Creates a new tensor with the same shape as input, filled with zeros.

In [4]:
import torch

In [6]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
torch.zeros_like(tensor)

tensor([[0, 0, 0],
        [0, 0, 0]])

torch.ones_like(input)
* Creates a tensor filled with ones, matching shape and attributes of input

In [8]:
torch.ones_like(tensor)

tensor([[1, 1, 1],
        [1, 1, 1]])

torch.empty_like(input)
* Creates a tensor of the same size as input, but with random garbage values (not zero, not one, just whatever is in memory).

In [10]:
torch.empty_like(tensor)

tensor([[3616445622929465956, 6067809043591802165, 4120857642031265585],
        [6499883075709253678, 7309453675965983778, 8315168162784306286]])