<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/pytorch003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape


(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

train test split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [8]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[-0.07811589, -0.68787833, -0.13827217, ..., -0.4131194 ,
        -0.92245588, -0.23410332],
       [-1.53858555, -0.15231093, -1.53112398, ..., -1.72077089,
         0.3863556 , -0.1853872 ],
       [-0.66601068, -0.76371088, -0.63241495, ..., -0.03785114,
        -0.19734801, -0.55423788],
       ...,
       [ 0.39393756, -1.50070849,  0.32264739, ..., -0.14446144,
        -0.965206  , -0.52907681],
       [ 0.53294717,  0.23870066,  0.50894973, ...,  0.53175247,
         1.78560003,  1.1658162 ],
       [-0.4603923 , -1.62393639, -0.4898495 , ..., -0.29051756,
        -0.13157859, -0.90542229]])

In [10]:
y_train

51     B
314    B
422    B
55     B
115    B
      ..
272    M
193    M
209    B
223    M
170    B
Name: diagnosis, Length: 455, dtype: object

label encoding

In [11]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

numpy arrays to pytorch tensors

In [13]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)


In [14]:
X_train_tensor

tensor([[-0.0781, -0.6879, -0.1383,  ..., -0.4131, -0.9225, -0.2341],
        [-1.5386, -0.1523, -1.5311,  ..., -1.7208,  0.3864, -0.1854],
        [-0.6660, -0.7637, -0.6324,  ..., -0.0379, -0.1973, -0.5542],
        ...,
        [ 0.3939, -1.5007,  0.3226,  ..., -0.1445, -0.9652, -0.5291],
        [ 0.5329,  0.2387,  0.5089,  ...,  0.5318,  1.7856,  1.1658],
        [-0.4604, -1.6239, -0.4898,  ..., -0.2905, -0.1316, -0.9054]],
       dtype=torch.float64)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [26]:
class MySimpleNN():

  def __init__(self,X):
    self.weights=torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True) # initially 0 and only 1 bias

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss(self,y_pred,y):
    # clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #calculate loss
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

important parameters

In [27]:
learning_rate=0.1
epochs=25

training pipeline

In [45]:
# create model
model=MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred=model.forward(X_train_tensor)

  # loss calculate
  loss=model.loss(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  # paramters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.9226242565444907
Epoch: 2, Loss: 1.8058848316875482
Epoch: 3, Loss: 1.6986977865200679
Epoch: 4, Loss: 1.5985606607123375
Epoch: 5, Loss: 1.5116278320563192
Epoch: 6, Loss: 1.437464706306823
Epoch: 7, Loss: 1.3751312875357604
Epoch: 8, Loss: 1.3233279896906633
Epoch: 9, Loss: 1.2805516841044031
Epoch: 10, Loss: 1.2452317223803935
Epoch: 11, Loss: 1.2158772351263183
Epoch: 12, Loss: 1.1911938433126932
Epoch: 13, Loss: 1.1701277694047372
Epoch: 14, Loss: 1.1518523417201503
Epoch: 15, Loss: 1.13573187515187
Epoch: 16, Loss: 1.1212838312764573
Epoch: 17, Loss: 1.1081457916118904
Epoch: 18, Loss: 1.0960480193908702
Epoch: 19, Loss: 1.0847911459022002
Epoch: 20, Loss: 1.0742283999803872
Epoch: 21, Loss: 1.0642517711475352
Epoch: 22, Loss: 1.0547814643862456
Epoch: 23, Loss: 1.0457580129787853
Epoch: 24, Loss: 1.037136472361403
Epoch: 25, Loss: 1.0288822030053224


In [34]:
model.bias

tensor([-0.2361], dtype=torch.float64, requires_grad=True)

In [36]:
model.weights

tensor([[-0.4375],
        [-1.1909],
        [-1.3048],
        [-0.4286],
        [ 0.1508],
        [-1.1804],
        [ 1.3446],
        [ 0.3684],
        [-0.7168],
        [ 1.1060],
        [ 0.3663],
        [-1.0734],
        [ 1.3609],
        [ 0.2053],
        [-0.2573],
        [ 0.3935],
        [-1.0346],
        [ 0.3070],
        [-0.0967],
        [ 0.1977],
        [ 1.1912],
        [ 1.1782],
        [ 0.0505],
        [-1.0178],
        [-0.9454],
        [-0.4311],
        [-1.1899],
        [ 1.2849],
        [ 0.6211],
        [-0.3978]], dtype=torch.float64, requires_grad=True)

model evaluation

In [46]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5541704893112183
