<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/random_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# torch.randint() — Random Integers in a Range

Generates integers between low (inclusive) and high (exclusive).
Generates a tensor with random integers between a given range (low, high)

In [2]:
import torch

In [3]:
tensor_a=torch.randint(low=0,high=10,size=(2,4))
tensor_a

tensor([[3, 5, 0, 1],
        [2, 1, 4, 3]])

# torch.rand() — Uniform Distribution

Generates a tensor filled with random numbers from a uniform distribution in the range [0, 1].
Simply understand this: Use `torch.rand()` when you want values between 0 and 1.

## Parameters:
- `size (tuple of ints)`: Shape of the tensor (e.g., (2, 3), (4,), etc.).
- `dtype (optional)`: Data type of the tensor (e.g., torch.float32, torch.float64). Defaults to float.
- `device (optional)`: Where to create the tensor: 'cpu' or 'cuda' for GPU.
- `requires_grad (optional)`: Set to True if you want to track operations for gradient computation (used in training neural networks).

- When you want random values equally likely between 0 and 1.
- Often used in weight initialization, data simulation, or probability sampling.

In [4]:
torch.rand(2,3)

tensor([[0.7425, 0.5818, 0.6432],
        [0.1877, 0.5892, 0.7446]])

# torch.randn() — Normal (Gaussian) Distribution

Returns values sampled from a normal distribution with mean = 0 and standard deviation = 1.

## Parameters:
- `size (tuple of ints)`: Shape of the tensor (e.g., (2, 3), (4,), etc.).
- `dtype (optional)`: Data type of the tensor (e.g., torch.float32, torch.float64). Defaults to float.
- `device (optional)`: Where to create the tensor: 'cpu' or 'cuda' for GPU.
- `requires_grad (optional)`: Set to True if you want to track operations for gradient computation (used in training neural networks).

- When you want random values from a standard normal distribution.
- Often used in weight initialization, adding noise, or simulations.

In [5]:
torch.randn(2,3)

tensor([[ 3.1986, -1.0507,  1.4998],
        [-0.5696, -1.6225,  0.7863]])