<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/Tensor_initialization2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# torch.full() — Fill Tensor with Custom Value

`torch.full()` creates a tensor of a specified shape where every element is initialized to the same constant value.

- `torch.full(size, fill_value)`
- Creates a tensor of the given size, and fills every element with `fill_value`.
- Useful for custom initializations, e.g., when you want all weights to start at a specific number.
- Useful in masking, bias initialization, or constant matrix operations

## Parameters:
- `size (tuple of ints)`
- `fill_value (scalar)`
- `dtype (optional)`
- `device (optional)`
- `requires_grad (optional, default=False)`

In [1]:
import torch

In [3]:
tensor_full=torch.full((2,3), 5)
tensor_full

tensor([[5, 5, 5],
        [5, 5, 5]])

In [4]:
torch.full(size=(2,2),fill_value=7,dtype=torch.float32,device='cpu',requires_grad=False)

tensor([[7., 7.],
        [7., 7.]])

# torch.eye() — Identity Matrix

`torch.eye()` creates a 2D identity matrix, i.e., a square matrix with 1s on the diagonal and 0s elsewhere.

- `torch.eye(n)` creates a 2D square identity matrix of size n x n.
- You can also use `torch.eye(n, m)` for a non-square identity matrix with n rows and m columns.

## Parameters:
- `n (int)`: Number of rows in the identity matrix.
- `m (optional, int)`: Number of columns. If not provided, defaults to n, making a square matrix.
- `dtype, device, requires_grad`

*Often used in linear algebra for identity matrix operations.
*Helpful in transformations, batch operations, and initializing weights to identity in some models.

In [6]:
tensor_a=torch.eye(10)

In [7]:
tensor_a

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
tensor_b=torch.eye(2,3)
tensor_b

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [10]:
torch.eye(n=3,m=4,dtype=torch.float32,device='cpu',requires_grad=False)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

# torch.diag() — Create Diagonal Matrix or Extract Diagonal

`torch.diag()` serves two purposes depending on input:
- If input is 1D, it returns a 2D diagonal matrix with that vector on the diagonal.
- If input is 2D, it returns a 1D vector of the diagonal elements.

## Parameters:
- `input (Tensor)`: Either a 1D or 2D tensor. Behavior changes based on this.
- `diagonal (optional, int, default=0)`: Specifies which diagonal to consider:
  - 0: main diagonal,
  - Positive: above main diagonal,
  - Negative: below main diagonal.

*When converting vectors to diagonal matrices or vice versa.
*Useful in custom matrix building, tracing, and diagonal scaling operations.

In [11]:
vector=torch.tensor([10,20,30])
torch.diag(vector)

tensor([[10,  0,  0],
        [ 0, 20,  0],
        [ 0,  0, 30]])

In [12]:
matrix=torch.tensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
torch.diag(matrix)

tensor([1, 5, 9])

In [14]:
vector=torch.tensor([10,20,30])
torch.diag(vector,diagonal=1)

tensor([[ 0, 10,  0,  0],
        [ 0,  0, 20,  0],
        [ 0,  0,  0, 30],
        [ 0,  0,  0,  0]])