<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Tensor Creation Explained:
torch.tensor(), torch.as_tensor(), torch.from_numpy()

Three fundamental functions to create tensors in PyTorch: torch.tensor(), torch.as_tensor(), and torch.from_numpy().


In [2]:
import torch


torch.tensor() creates a new tensor by copying data from a Python list, tuple, NumPy array, or scalar. It always copies the data, so the tensor and the original data do not share memory.

Parameters:
- data: The input data (e.g., list, tuple, or NumPy array) to convert into a tensor.
- dtype (optional): Specifies the data type, like torch.float32, torch.int64, or torch.bool. If not provided, PyTorch infers it from the input.
- device (optional): Defines where the tensor lives, like cpu or cuda for GPU. Default is CPU.
- requires_grad (optional): A boolean that, if True, tracks operations for gradient computation. Default is False.
- pin_memory (optional): If True, allocates the tensor in pinned memory for faster CPU-to-GPU transfers. Default is False.

Note: Since data is copied, modifying the tensor does NOT affect the original NumPy array

In [3]:
scalar=torch.tensor(5)
scalar

tensor(5)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

5

In [7]:
vector=torch.tensor([5,5])
vector

tensor([5, 5])

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
MATRIX=torch.tensor([[1,2,3],
                    [5,6,7]])
MATRIX

tensor([[1, 2, 3],
        [5, 6, 7]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [15]:
tensor=torch.tensor([[1,2,3],
                     [5,100,58],
                     [78,45,69],
                     [65,1,3]])
tensor

tensor([[  1,   2,   3],
        [  5, 100,  58],
        [ 78,  45,  69],
        [ 65,   1,   3]])

In [16]:
tensor.ndim

2

In [17]:
tensor.shape

torch.Size([4, 3])