<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/torch_tensor_vs_torch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

torch.tensor_vs_torch.Tensor

When passing a number it does not fill with the values , it creates uninitialized memory.(like torch.empty())

In [1]:
import torch

In [3]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [4]:
b=torch.Tensor(2,3) # It allocates some memory in our system but the values will be uninitialized , like some garbage values
b

tensor([[1.5260e-42, 4.3685e-41, 0.0000e+00],
        [0.0000e+00, 3.3631e-44, 0.0000e+00]])

In [5]:
torch.tensor(3)

tensor(3)

In [6]:
torch.Tensor(3)

tensor([1.6329e-38, 0.0000e+00, 1.6388e-38])

In [7]:
# to make the torch.Tensor(3) work similar to torch.tensor(3) use torch.Tensor([3])
torch.Tensor([3])

tensor([3.])