<a href="https://colab.research.google.com/github/akkiyolo/pytorch/blob/main/torch_rand_like_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### "Random like" functions generate random tensors with the same shape and other properties (like dtype, device, layout) as an existing tensor. Think of them as shortcuts to generate random values that are shaped like another tensor.

In [1]:
import torch

In [2]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

#### torch.rand_like(input)

Creates a tensor of the same shape as input, filled with uniformly distributed random numbers in the range [0,1].

In [3]:
torch.rand_like(tensor,dtype=torch.float)


tensor([[0.8652, 0.7955, 0.8554],
        [0.4542, 0.2274, 0.5896]])

#### torch.randn_like(input)

Creates a tensor with the same shape and attributes as input, filled with normally distributed (Gaussian) random numbers, where:
Mean = 0
Standard Deviation = 1

In [4]:
torch.randn_like(tensor,dtype=torch.float)

tensor([[-0.3537, -1.3254,  0.3635],
        [-0.1346,  0.3930,  0.2339]])

#### torch.randint_like(input, low, high)

Creates a tensor with the same shape and layout as input, filled with random integers in the range [low, high].
Note: Because if your base tensor is int type, then rand_like and randn_like won't work correctly unless you change dtype to float.

In [5]:
torch.randint_like(tensor,low=10,high=100)

tensor([[74, 80, 38],
        [75, 76, 54]])